[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-genai>=1.54.0",
    "pdf2image>=1.17.0",
    "pillow>=12.0.0",
    "python-docx>=1.2.0",
    "streamlit>=1.52.1",
]
